# Generated by Django 4.2.4 on 2023-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_user_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_loggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('search_period', models.DateTimeField()),
            ],
        ),
    ]
